version: 1.0.0.{build}

# Ideally we'd use this to set the version, but AV reads the version
# before it creates the VM and sets the env vars.
environment:
  semver: 1.0.0

services:
  - mssql2008r2sp2

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(semver).0"
  assembly_file_version: "{version}"
  assembly_informational_version: "$(semver)"
  
configuration: Release

before_build:
  - nuget restore
  # Fix the connection string in the test assembly before compilation
  - ps: (gc NHibernate.BlockGenerator.IntegrationTests\ConfigurationFactory.cs) | foreach {$_ -replace 'Server=LOCALHOST;Database=BlockGeneratorTest;Integrated Security=true', 'Server=(local)\SQL2008R2SP2;Database=BlockGeneratorTest;User ID=sa;Password=Password12!'} | sc NHibernate.BlockGenerator.IntegrationTests\ConfigurationFactory.cs

build:
  publish_nuget: true

before_test:
  - sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -i "database\create_database.sql"
  - sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -d "BlockGeneratorTest" -i "database\create_schema.sql"

artifacts:
  - path: NHibernate.BlockGenerator\bin\$(configuration)\NHibernate.BlockGenerator.dll
    name: NHibernate BlockGenerator

  - path: "*.nupkg"
    name: NHibernate BlockGenerator Nuget Package
